name: Java Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Selenium Test
      run: mvn exec:java -Dexec.mainClass="Q1.Q1"

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports

    - name: Upload Excel file
      uses: actions/upload-artifact@v2
      with:
        name: excel-file
        path: /Q1/src/test/java/Q1/Q1.xlsx
